version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass yourpassword
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local